//! Obfuscated built-in OAuth2 credentials.
//!
//! Generated by `build.rs` from `.env` or environment variables.
//! Uses `obfstr` to prevent plaintext extraction from the binary.

include!(concat!(env!("OUT_DIR"), "/_obfuscated_credentials.rs"));
