use crate::commands::types::HealthReport;

/// System-level signal from background tasks and internal scheduling.
///
/// These signals are generated by the executor itself or its spawned
/// background tasks — never by the UI layer. They are delivered via a
/// dedicated internal channel that is inaccessible to UI code.
#[derive(Debug)]
pub enum InternalCommand {
    /// Background HIBP health check completed with the final report.
    HealthCheckCompleted { report: HealthReport },

    /// Schedule a health check run (advisory, non-blocking).
    ScheduleHealthCheck { force: bool },
}

#[cfg(test)]
mod exhaustive_tests {
    use super::*;

    /// Compile-time exhaustiveness check.
    /// Adding a new InternalCommand variant without updating this match will
    /// cause a compile error.
    #[test]
    fn internal_command_exhaustive_match() {
        fn _assert_exhaustive(cmd: InternalCommand) {
            match cmd {
                InternalCommand::HealthCheckCompleted { .. } => {}
                InternalCommand::ScheduleHealthCheck { .. } => {}
            }
        }
    }
}
